version: '3.9'

services:
  api:
    build:
      context: .
      target: dev
    container_name: yodds-api
    volumes:
      - ./dist:/app/dist:delegated
    environment:
      - WS_USERNAME=${WS_USERNAME}
      - WS_PASSWORD=${WS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 5000:5000
