version: '3.9'

services:
  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  api:
    build:
      context: .
      target: dev
    container_name: yodds-api
    depends_on:
      - cache
    volumes:
      - ./dist:/app/dist:delegated
    environment:
      - WS_USERNAME=${WS_USERNAME}
      - WS_PASSWORD=${WS_PASSWORD}
      - REDIS_HOST=cache
    ports:
      - 5000:5000

volumes:
  cache:
    driver: local
